#!/bin/bash

# https://github.com/croyleje/eww-hyprland-workspace/blob/master/get-active-workspace

active_window (){
  echo $(hyprctl activewindow -j | jq '.initialTitle' || "hyprland") | tr -d '"'
}

active_window
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
  active_window
done
