#!/bin/bash

# https://github.com/croyleje/eww-hyprland-workspace/blob/master/get-active-workspace

active_workspace (){
  echo $(hyprctl monitors -j | jq '.[] | select(.focused) | .activeWorkspace.id')
}

active_workspace
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
  active_workspace
done
