# vim: filetype=hyprlang

wallpaper {
  monitor = # must be set, leaving it empty sets it as the default for all monitors
  path = ~/.config/hypr/wallpaper.png
}

splash = false # remove text at the bottom of the screen
